# Generated by Django 3.2.3 on 2021-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=500)),
                ('product_price', models.FloatField(default=0)),
                ('product_image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
